version: '3.8'

services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports:
            - "5432:5432"


    redis:
        image: redis:latest
        ports:
            - "6379:6379"