database:
    default: main
    databases:
        main:
            platform: 'pgsql'
            host: '0.0.0.0'
            port: 5432
            database: 'main'
            user: 'main'
            password: 'main'
