monolog:
    default: app

    channels:
        app:
            handlers:
                - monolog.handler.stderr

            processors:
                - monolog.processor.psr-log-message
                - monolog.processor.process-id

        http:
            handlers:
                - monolog.handler.stderr

            processors:
                - monolog.processor.psr-log-message
                - monolog.processor.process-id

    handlers:
        stderr:
            type: stderr
            level: debug
            formatter: monolog.formatter.console
